name: aoc-day1
version: 0.1.0.0

dependencies:
  - base
  - array

library:
  exposed-modules: AocDay1
  source-dirs: src
  dependencies:

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aoc-day1
      - hspec
